# Site settings
title: JekyllHelp Help
relative_permalinks: true
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

collections:
  English.lproj:
    output: true
  Japanese.lproj:
    output: true
  Dutch.lproj:
    output: true
  French.lproj:
    output: true
  Italian.lproj:
    output: true
  German.lproj:
    output: true
  Spanish.lproj:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "help"
      order: 0

exclude: ['Makefile', 'jekyll-server.command', 'Info.plist']
